In [1]:
import numpy as np
import pandas as pd #data analysis

In [3]:
data=pd.read_csv("./fraud_transactions_synthetic.csv")

In [5]:
data.head() #head() allows us to display the first 5 records of the dataset

,amount,hour,distance_km,failed_logins_24h,is_international,is_new_device,account_age_days,txn_velocity_1h,prev_chargebacks,merchant_risk_score,is_fraud
0,33.006818,15,5.500706,1,0,0,1968,1,0,0.141327,0
1,17.491861,2,45.404859,0,0,0,883,2,1,0.249084,0
2,38.385836,5,1.889033,0,0,0,257,0,0,0.175303,0
3,92.114269,19,7.925388,0,0,0,3025,3,0,0.060368,0
4,15.892489,3,45.704719,0,0,0,1651,1,0,0.274630,1

In [6]:
data.shape #here we have 40,000 rows and 11 columns
#out of 11 columns, 10 columns/features are belonging to the independent category - they are the input features to the NN
#and only 1 is a dependent column

(40000, 11)

In [7]:
import tensorflow as tf
from tensorflow import keras #one of the most important modules within Tensorflow
from tensorflow.keras import layers #layers will help us in developing the neural network layers

In [8]:
#divide the data into dependent and independent colums
x=data.drop(['is_fraud'],axis=1) #stores the independent columnns
y=data['is_fraud'] #stores the dependent or the target column

In [9]:
x.head()

,amount,hour,distance_km,failed_logins_24h,is_international,is_new_device,account_age_days,txn_velocity_1h,prev_chargebacks,merchant_risk_score
0,33.006818,15,5.500706,1,0,0,1968,1,0,0.141327
1,17.491861,2,45.404859,0,0,0,883,2,1,0.249084
2,38.385836,5,1.889033,0,0,0,257,0,0,0.175303
3,92.114269,19,7.925388,0,0,0,3025,3,0,0.060368
4,15.892489,3,45.704719,0,0,0,1651,1,0,0.274630

In [10]:
y.head()

0    0
1    0
2    0
3    0
4    1
Name: is_fraud, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [13]:
x_train.shape

(30000, 10)

In [14]:
x_test.head()

,amount,hour,distance_km,failed_logins_24h,is_international,is_new_device,account_age_days,txn_velocity_1h,prev_chargebacks,merchant_risk_score
30120,58.373980,20,87.557787,1,0,0,893,3,0,0.050762
8791,13.145755,18,38.788110,1,0,0,375,0,0,0.114395
30956,6.333714,7,15.734310,0,0,0,1338,1,0,0.112871
30481,14.769550,22,2.143419,1,0,1,2795,2,0,0.135089
15175,37.794048,9,9.271145,0,0,0,2921,1,0,0.212893

In [15]:
x_test.shape

(10000, 10)

In [16]:
x_train.shape[1] #total of 10 neurons are required for us to create the input layer of the NN

10

In [34]:
#building the NN using Tensorflow and Keras - we build it like a Sequential Model with layers stacked on top of each other
model=keras.Sequential([
    layers.Input(shape=(x_train.shape[1],),name='input_layer'), #input_layer has 10 neurons
    layers.Dense(16,activation='tanh',name='hidden_layer_1'), #hidden_layer_1 has 16 neurons
    layers.Dense(32,activation='relu',name='hidden_layer_2'), #hidden_layer_2 has 32 neurons
    layers.Dense(1,activation='sigmoid',name='output_layer') #output_layer has just 1 neuron since it is a binary classifier
])

In [35]:
model.compile(
    optimizer='adam', #optimizer will ensure that the gradient loss is within the range
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [36]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9417 - loss: 0.2248
Epoch 2/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9417 - loss: 0.2231
Epoch 3/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9417 - loss: 0.2227
Epoch 4/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9417 - loss: 0.2230
Epoch 5/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9417 - loss: 0.2222
Epoch 6/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9417 - loss: 0.2229
Epoch 7/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9417 - loss: 0.2228
Epoch 8/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9417 - loss: 0.2228
Epoch 9/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9417 - loss: 0.2227
Epoch 10/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9417 - loss: 0.2230

In [37]:
y_pred=model.predict(x_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [38]:
print(y_pred)

[[0.05344905]
 [0.05344893]
 [0.05344893]
 ...
 [0.05344893]
 [0.05344893]
 [0.05344893]]