In [223]:

import numpy as np
import pandas as pd #data analysis

In [224]:
data=pd.read_csv("diabetes.csv")

In [225]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [226]:
data.shape

(768, 9)

In [227]:
import tensorflow as tf
from tensorflow import keras #one of the most important modules within Tensorflow
from tensorflow.keras import layers #layers will help us in developing the neural network layers

In [228]:
#divide the data into dependent and independent colums
x=data.drop(['Outcome'],axis=1) #stores the independent columnns
y=data['Outcome'] #stores the dependent or the target column

In [229]:


x.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [230]:

y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [231]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [232]:
x_train.shape

(614, 8)

In [233]:
model=keras.Sequential([
    layers.Input(shape=(x_train.shape[1],),name='input_layer'), #input_layer has 8 neurons
    layers.Dense(16,activation='relu',name='hidden_layer_1'), #hidden_layer_1 has 16 neurons
    # layers.Dense(32,activation='relu',name='hidden_layer_2'), #hidden_layer_2 has 32 neurons
    # layers.Dense(16,activation='relu',name='hidden_layer_3'), #hidden_layer_3 has 16 neurons
    layers.Dense(8,activation='relu',name='hidden_layer_4'), #hidden_layer_4 has 8 neurons
    layers.Dense(1,activation='sigmoid',name='output_layer') #output_layer has just 1 neuron since it is a binary classifier
])

In [234]:

model.compile(
    optimizer='adam', #optimizer will ensure that the gradient loss is within the range
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [235]:

model.fit(x_train,y_train,epochs=50,batch_size=8)

Epoch 1/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5326 - loss: 7.0285
Epoch 2/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6303 - loss: 2.0859
Epoch 3/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6270 - loss: 1.6530
Epoch 4/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5847 - loss: 1.3451
Epoch 5/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5619 - loss: 1.1793
Epoch 6/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5847 - loss: 1.0827
Epoch 7/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6091 - loss: 0.9998
Epoch 8/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6287 - loss: 0.9452
Epoch 9/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5700 - loss: 0.9970
Epoch 10/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5879 - loss: 0.8837
Epoch 11/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6042 - loss: 0.8607
Epoch 12/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6091 - loss: 0.8077
Epoch 13/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6319 - loss: 0.8054
Epoch 14/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6319 - loss: 0.7537
Epoch 15/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6303 - loss: 0.7378
Epoch 16/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6482 - loss: 0.7202
Epoch 17/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6596 - loss: 0.7283
Epoch 18/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6368 - loss: 0.7129
Epoch 19/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6596 - loss: 0.6964
Epoch 20/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6482 - loss: 0.6849
Epoch 21/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6900
Epoch 22/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6906 - loss: 0.6500
Epoch 23/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6678 - loss: 0.6605
Epoch 24/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6424
Epoch 25/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6596 - loss: 0.6503
Epoch 26/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6792 - loss: 0.6296
Epoch 27/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.6313
Epoch 28/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6792 - loss: 0.6434
Epoch 29/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6873 - loss: 0.6126
Epoch 30/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6906 - loss: 0.6248
Epoch 31/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6971 - loss: 0.6158
Epoch 32/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6889 - loss: 0.6084
Epoch 33/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6971 - loss: 0.6261
Epoch 34/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6938 - loss: 0.5977
Epoch 35/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7003 - loss: 0.5988
Epoch 36/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6824 - loss: 0.6389
Epoch 37/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7052 - loss: 0.5869
Epoch 38/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6971 - loss: 0.6056
Epoch 39/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6987 - loss: 0.5981
Epoch 40/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7199 - loss: 0.6038
Epoch 41/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6971 - loss: 0.6095
Epoch 42/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7036 - loss: 0.5809
Epoch 43/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7101 - loss: 0.5923
Epoch 44/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7264 - loss: 0.5741
Epoch 45/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7020 - loss: 0.5948
Epoch 46/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6824 - loss: 0.6076
Epoch 47/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7085 - loss: 0.5777
Epoch 48/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6987 - loss: 0.5733
Epoch 49/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7101 - loss: 0.5775
Epoch 50/50
77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7003 - loss: 0.5683

In [236]:
loss, accuracy = model.evaluate(x_test, y_test)
print("Accuracy:", accuracy)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7078 - loss: 0.5827
Accuracy: 0.7077922224998474

In [237]:

y_pred=model.predict(x_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

In [238]:

print(y_pred)

[[0.24227096]
 [0.19296037]
 [0.2598715 ]
 [0.08614372]
 [0.40447935]
 [0.6422123 ]
 [0.15116942]
 [0.66658777]
 [0.32769397]
 [0.4413123 ]
 [0.3226278 ]
 [0.29477492]
 [0.8455346 ]
 [0.8059028 ]
 [0.1334737 ]
 [0.33442622]
 [0.45423728]
 [0.862001  ]
 [0.75409085]
 [0.51262903]
 [0.5362245 ]
 [0.2725675 ]
 [0.4205103 ]
 [0.5152924 ]
 [0.5719713 ]
 [0.25898132]
 [0.0616373 ]
 [0.19369017]
 [0.3051077 ]
 [0.49694297]
 [0.09084938]
 [0.07044518]
 [0.2405439 ]
 [0.41566017]
 [0.45459145]
 [0.3060102 ]
 [0.38357154]
 [0.4744702 ]
 [0.07221416]
 [0.34589946]
 [0.29335022]
 [0.3559016 ]
 [0.74701   ]
 [0.33916983]
 [0.3500504 ]
 [0.4844192 ]
 [0.23064782]
 [0.14119749]
 [0.9405444 ]
 [0.05179079]
 [0.55399   ]
 [0.8682201 ]
 [0.6977144 ]
 [0.4478711 ]
 [0.8217239 ]
 [0.49639595]
 [0.14048074]
 [0.62391615]
 [0.8002068 ]
 [0.14305219]
 [0.2368639 ]
 [0.56019115]
 [0.22499573]
 [0.19370596]
 [0.01233865]
 [0.43163332]
 [0.41616756]
 [0.07066732]
 [0.20199014]
 [0.18829398]
 [0.16052155]
 [0.22727361]
 [0.4589846 ]
 [0.21999606]
 [0.2370652 ]
 [0.13688222]
 [0.8208707 ]
 [0.30302638]
 [0.6821506 ]
 [0.05628353]
 [0.07316978]
 [0.31529126]
 [0.09957351]
 [0.07104806]
 [0.85647017]
 [0.33575156]
 [0.28920877]
 [0.06651929]
 [0.18609047]
 [0.48163885]
 [0.7250756 ]
 [0.3215087 ]
 [0.13263346]
 [0.35040438]
 [0.43872732]
 [0.36838788]
 [0.78837186]
 [0.2863534 ]
 [0.15795662]
 [0.22432652]
 [0.76400787]
 [0.27809292]
 [0.18041636]
 [0.26856765]
 [0.37590727]
 [0.20843919]
 [0.18051067]
 [0.54193723]
 [0.19409956]
 [0.18957144]
 [0.09071517]
 [0.5851246 ]
 [0.870577  ]
 [0.23817375]
 [0.29242203]
 [0.4805578 ]
 [0.44184425]
 [0.43777   ]
 [0.14046398]
 [0.25999084]
 [0.19681124]
 [0.4065293 ]
 [0.2963542 ]
 [0.39209664]
 [0.18074907]
 [0.19326115]
 [0.324416  ]
 [0.8318374 ]
 [0.23820004]
 [0.22288296]
 [0.7912297 ]
 [0.08707503]
 [0.14448644]
 [0.29029372]
 [0.47408748]
 [0.22407413]
 [0.28969726]
 [0.33416376]
 [0.62627745]
 [0.6956998 ]
 [0.16319749]
 [0.03301496]
 [0.03166331]
 [0.2785107 ]
 [0.5355407 ]
 [0.61140245]
 [0.1657693 ]
 [0.37556872]
 [0.13817698]
 [0.22932103]
 [0.5176629 ]
 [0.32729712]
 [0.26587   ]
 [0.6844801 ]]